(cl:in-package NatRosPkg-msg)
(cl:export '(HEADER-VAL
          HEADER
          NAT_SERVER_SYSTEMLATENCYMILLISEC-VAL
          NAT_SERVER_SYSTEMLATENCYMILLISEC
          NAT_SERVER_CLIENTLATENCYMILLISEC-VAL
          NAT_SERVER_CLIENTLATENCYMILLISEC
          NAT_SERVER_TRANSITLATENCYMILLISEC-VAL
          NAT_SERVER_TRANSITLATENCYMILLISEC
          NAT_SERVER_TIMESTAMP-VAL
          NAT_SERVER_TIMESTAMP
          NAT_SERVER_TIMECODE-VAL
          NAT_SERVER_TIMECODE
          NAT_SERVER_FRAMEID-VAL
          NAT_SERVER_FRAMEID
          MARKERS-VAL
          MARKERS
          BODIES-VAL
          BODIES
          SKELETONS-VAL
          SKELETONS
          DEVICES-VAL
          DEVICES
          FORCEPLATES-VAL
          FORCEPLATES
))