// Generated by gencpp from file NatRosPkg/body.msg
// DO NOT EDIT!


#ifndef NATROSPKG_MESSAGE_BODY_H
#define NATROSPKG_MESSAGE_BODY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace NatRosPkg
{
template <class ContainerAllocator>
struct body_
{
  typedef body_<ContainerAllocator> Type;

  body_()
    : id(0)
    , pose()
    , meanError(0.0)
    , isValid(false)
    , params(0)  {
    }
  body_(const ContainerAllocator& _alloc)
    : id(0)
    , pose(_alloc)
    , meanError(0.0)
    , isValid(false)
    , params(0)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef double _meanError_type;
  _meanError_type meanError;

   typedef uint8_t _isValid_type;
  _isValid_type isValid;

   typedef int16_t _params_type;
  _params_type params;





  typedef boost::shared_ptr< ::NatRosPkg::body_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::NatRosPkg::body_<ContainerAllocator> const> ConstPtr;

}; // struct body_

typedef ::NatRosPkg::body_<std::allocator<void> > body;

typedef boost::shared_ptr< ::NatRosPkg::body > bodyPtr;
typedef boost::shared_ptr< ::NatRosPkg::body const> bodyConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::NatRosPkg::body_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::NatRosPkg::body_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::NatRosPkg::body_<ContainerAllocator1> & lhs, const ::NatRosPkg::body_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.pose == rhs.pose &&
    lhs.meanError == rhs.meanError &&
    lhs.isValid == rhs.isValid &&
    lhs.params == rhs.params;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::NatRosPkg::body_<ContainerAllocator1> & lhs, const ::NatRosPkg::body_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace NatRosPkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::NatRosPkg::body_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::NatRosPkg::body_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::NatRosPkg::body_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::NatRosPkg::body_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::NatRosPkg::body_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::NatRosPkg::body_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::NatRosPkg::body_<ContainerAllocator> >
{
  static const char* value()
  {
    return "647dbfe684b15d34fa5bec37c45720ac";
  }

  static const char* value(const ::NatRosPkg::body_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x647dbfe684b15d34ULL;
  static const uint64_t static_value2 = 0xfa5bec37c45720acULL;
};

template<class ContainerAllocator>
struct DataType< ::NatRosPkg::body_<ContainerAllocator> >
{
  static const char* value()
  {
    return "NatRosPkg/body";
  }

  static const char* value(const ::NatRosPkg::body_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::NatRosPkg::body_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 id\n"
"geometry_msgs/Pose pose\n"
"float64 meanError\n"
"bool isValid\n"
"int16 params\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::NatRosPkg::body_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::NatRosPkg::body_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.pose);
      stream.next(m.meanError);
      stream.next(m.isValid);
      stream.next(m.params);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct body_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::NatRosPkg::body_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::NatRosPkg::body_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "meanError: ";
    Printer<double>::stream(s, indent + "  ", v.meanError);
    s << indent << "isValid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isValid);
    s << indent << "params: ";
    Printer<int16_t>::stream(s, indent + "  ", v.params);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NATROSPKG_MESSAGE_BODY_H
