// Generated by gencpp from file NatRosPkg/markers.msg
// DO NOT EDIT!


#ifndef NATROSPKG_MESSAGE_MARKERS_H
#define NATROSPKG_MESSAGE_MARKERS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <NatRosPkg/marker.h>

namespace NatRosPkg
{
template <class ContainerAllocator>
struct markers_
{
  typedef markers_<ContainerAllocator> Type;

  markers_()
    : nMarkers(0)
    , markers()  {
    }
  markers_(const ContainerAllocator& _alloc)
    : nMarkers(0)
    , markers(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _nMarkers_type;
  _nMarkers_type nMarkers;

   typedef std::vector< ::NatRosPkg::marker_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::NatRosPkg::marker_<ContainerAllocator> >> _markers_type;
  _markers_type markers;





  typedef boost::shared_ptr< ::NatRosPkg::markers_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::NatRosPkg::markers_<ContainerAllocator> const> ConstPtr;

}; // struct markers_

typedef ::NatRosPkg::markers_<std::allocator<void> > markers;

typedef boost::shared_ptr< ::NatRosPkg::markers > markersPtr;
typedef boost::shared_ptr< ::NatRosPkg::markers const> markersConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::NatRosPkg::markers_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::NatRosPkg::markers_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::NatRosPkg::markers_<ContainerAllocator1> & lhs, const ::NatRosPkg::markers_<ContainerAllocator2> & rhs)
{
  return lhs.nMarkers == rhs.nMarkers &&
    lhs.markers == rhs.markers;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::NatRosPkg::markers_<ContainerAllocator1> & lhs, const ::NatRosPkg::markers_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace NatRosPkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::NatRosPkg::markers_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::NatRosPkg::markers_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::NatRosPkg::markers_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::NatRosPkg::markers_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::NatRosPkg::markers_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::NatRosPkg::markers_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::NatRosPkg::markers_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a1ca0ae52443593a08f786db6e001040";
  }

  static const char* value(const ::NatRosPkg::markers_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa1ca0ae52443593aULL;
  static const uint64_t static_value2 = 0x08f786db6e001040ULL;
};

template<class ContainerAllocator>
struct DataType< ::NatRosPkg::markers_<ContainerAllocator> >
{
  static const char* value()
  {
    return "NatRosPkg/markers";
  }

  static const char* value(const ::NatRosPkg::markers_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::NatRosPkg::markers_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 nMarkers\n"
"marker[] markers\n"
"================================================================================\n"
"MSG: NatRosPkg/marker\n"
"int32 ID\n"
"int32 modelID\n"
"geometry_msgs/Point position\n"
"float64 size\n"
"int16 params\n"
"float64 residual\n"
"\n"
"\n"
"bool oclluded \n"
"bool PCSolved \n"
"bool ModelSolved \n"
"bool HasModel \n"
"bool Unlabled \n"
"bool ActiveMarker \n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::NatRosPkg::markers_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::NatRosPkg::markers_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.nMarkers);
      stream.next(m.markers);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct markers_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::NatRosPkg::markers_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::NatRosPkg::markers_<ContainerAllocator>& v)
  {
    s << indent << "nMarkers: ";
    Printer<int32_t>::stream(s, indent + "  ", v.nMarkers);
    s << indent << "markers[]" << std::endl;
    for (size_t i = 0; i < v.markers.size(); ++i)
    {
      s << indent << "  markers[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::NatRosPkg::marker_<ContainerAllocator> >::stream(s, indent + "    ", v.markers[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // NATROSPKG_MESSAGE_MARKERS_H
