# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from NatRosPkg/channel.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class channel(genpy.Message):
  _md5sum = "3fa6a6187541c2c904521c296745a24b"
  _type = "NatRosPkg/channel"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int32 nFrames
float64[] Values
bool isEmpty
bool isPartial
"""
  __slots__ = ['nFrames','Values','isEmpty','isPartial']
  _slot_types = ['int32','float64[]','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       nFrames,Values,isEmpty,isPartial

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(channel, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.nFrames is None:
        self.nFrames = 0
      if self.Values is None:
        self.Values = []
      if self.isEmpty is None:
        self.isEmpty = False
      if self.isPartial is None:
        self.isPartial = False
    else:
      self.nFrames = 0
      self.Values = []
      self.isEmpty = False
      self.isPartial = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.nFrames
      buff.write(_get_struct_i().pack(_x))
      length = len(self.Values)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.Values))
      _x = self
      buff.write(_get_struct_2B().pack(_x.isEmpty, _x.isPartial))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (self.nFrames,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.Values = s.unpack(str[start:end])
      _x = self
      start = end
      end += 2
      (_x.isEmpty, _x.isPartial,) = _get_struct_2B().unpack(str[start:end])
      self.isEmpty = bool(self.isEmpty)
      self.isPartial = bool(self.isPartial)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.nFrames
      buff.write(_get_struct_i().pack(_x))
      length = len(self.Values)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.Values.tostring())
      _x = self
      buff.write(_get_struct_2B().pack(_x.isEmpty, _x.isPartial))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (self.nFrames,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.Values = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      _x = self
      start = end
      end += 2
      (_x.isEmpty, _x.isPartial,) = _get_struct_2B().unpack(str[start:end])
      self.isEmpty = bool(self.isEmpty)
      self.isPartial = bool(self.isPartial)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2B = None
def _get_struct_2B():
    global _struct_2B
    if _struct_2B is None:
        _struct_2B = struct.Struct("<2B")
    return _struct_2B
_struct_i = None
def _get_struct_i():
    global _struct_i
    if _struct_i is None:
        _struct_i = struct.Struct("<i")
    return _struct_i
