# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from NatRosPkg/forcePlate.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import NatRosPkg.msg

class forcePlate(genpy.Message):
  _md5sum = "78b6575faa3bd78870aadb6231f51303"
  _type = "NatRosPkg/forcePlate"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int32 id
int32 nChannels 
int16 params
channel[] channels
================================================================================
MSG: NatRosPkg/channel
int32 nFrames
float64[] Values
bool isEmpty
bool isPartial
"""
  __slots__ = ['id','nChannels','params','channels']
  _slot_types = ['int32','int32','int16','NatRosPkg/channel[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       id,nChannels,params,channels

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(forcePlate, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.id is None:
        self.id = 0
      if self.nChannels is None:
        self.nChannels = 0
      if self.params is None:
        self.params = 0
      if self.channels is None:
        self.channels = []
    else:
      self.id = 0
      self.nChannels = 0
      self.params = 0
      self.channels = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2ih().pack(_x.id, _x.nChannels, _x.params))
      length = len(self.channels)
      buff.write(_struct_I.pack(length))
      for val1 in self.channels:
        _x = val1.nFrames
        buff.write(_get_struct_i().pack(_x))
        length = len(val1.Values)
        buff.write(_struct_I.pack(length))
        pattern = '<%sd'%length
        buff.write(struct.Struct(pattern).pack(*val1.Values))
        _x = val1
        buff.write(_get_struct_2B().pack(_x.isEmpty, _x.isPartial))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.channels is None:
        self.channels = None
      end = 0
      _x = self
      start = end
      end += 10
      (_x.id, _x.nChannels, _x.params,) = _get_struct_2ih().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.channels = []
      for i in range(0, length):
        val1 = NatRosPkg.msg.channel()
        start = end
        end += 4
        (val1.nFrames,) = _get_struct_i().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sd'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.Values = s.unpack(str[start:end])
        _x = val1
        start = end
        end += 2
        (_x.isEmpty, _x.isPartial,) = _get_struct_2B().unpack(str[start:end])
        val1.isEmpty = bool(val1.isEmpty)
        val1.isPartial = bool(val1.isPartial)
        self.channels.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2ih().pack(_x.id, _x.nChannels, _x.params))
      length = len(self.channels)
      buff.write(_struct_I.pack(length))
      for val1 in self.channels:
        _x = val1.nFrames
        buff.write(_get_struct_i().pack(_x))
        length = len(val1.Values)
        buff.write(_struct_I.pack(length))
        pattern = '<%sd'%length
        buff.write(val1.Values.tostring())
        _x = val1
        buff.write(_get_struct_2B().pack(_x.isEmpty, _x.isPartial))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.channels is None:
        self.channels = None
      end = 0
      _x = self
      start = end
      end += 10
      (_x.id, _x.nChannels, _x.params,) = _get_struct_2ih().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.channels = []
      for i in range(0, length):
        val1 = NatRosPkg.msg.channel()
        start = end
        end += 4
        (val1.nFrames,) = _get_struct_i().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sd'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.Values = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
        _x = val1
        start = end
        end += 2
        (_x.isEmpty, _x.isPartial,) = _get_struct_2B().unpack(str[start:end])
        val1.isEmpty = bool(val1.isEmpty)
        val1.isPartial = bool(val1.isPartial)
        self.channels.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2B = None
def _get_struct_2B():
    global _struct_2B
    if _struct_2B is None:
        _struct_2B = struct.Struct("<2B")
    return _struct_2B
_struct_2ih = None
def _get_struct_2ih():
    global _struct_2ih
    if _struct_2ih is None:
        _struct_2ih = struct.Struct("<2ih")
    return _struct_2ih
_struct_i = None
def _get_struct_i():
    global _struct_i
    if _struct_i is None:
        _struct_i = struct.Struct("<i")
    return _struct_i
